config/routes.rb
Rails.application.routes.draw do
  root "recipes#index"
  resources :recipes
  resources :ingredients
#changing route
  get '/recipes/:id/add_ingredients' => 'recipes#add_ingredients', as: 'add_ingredients'
  post '/recipes/:id/add_ingredients' => 'recipes#create_ingredients'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord

  has_many :recipe_ingredients
  has_many :recipes, through: :recipe_ingredients

  
    
  
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  
  has_many :recipe_ingredients
  has_many :ingredients, through: :recipe_ingredients
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
  belongs_to :ingredient
  belongs_to :recipe
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

  def index
    @ingredients = Ingredient.all
  end

  def new
    @ingredient = Ingredient.new
  end

  def create
    @ingredient = Ingredient.create(ingredient_params)
    if @ingredient.valid?
      redirect_to ingredients_path
    else
      render :new, status: :unprocessable_entity
    end
  end

private

  def ingredient_params
    params.require(:ingredient).permit(:name)
  end
end

app/controllers/recipe_controller.rb
class RecipeController < ApplicationController

  def index
    @recipes = Recipe.all
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.create(recipe_params)
    if @recipe.valid?
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def reciple_params
    params.require(:recipe).permit(:calories, :people_fed, :cook_time, :course)
  end
end

app/controllers/recipe_ingredients_controller.rb
class RecipeIngredientsController < ApplicationController

  def new
    @recipe_ingredients = RecipeIngredient.new
  end

  def create
    @recipe_ingredient = RecipeIngredient(recipe_ingredient_params)
  end

#unsure of this edit function
  # def edit
  #   @recipe_ingredient = RecipeIngredient.find(params[:id])
  # end
#ending uncertainty

  # def update
  #   redirect_to root_path
  # end


  def recipe_ingredient_params
    params.require(:recipe_ingredient).permit(:quantity)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.create(recipe_params)
    if @recipe.valid?
      redirect_to add_ingredients_path(@recipe.id)
    else
      #returns an array of all the error messages
      flash[:danger] = @recipe.errors.full_messages
      render :new
    end

#unsure of this edit controller function...
    # def edit
    #   @recipe = Recipe.find(params[:ingredient_id])
    #   @ingredient = Ingredient.find(params[:id])
    # end

    # ending expirment

    #again unsure of the update..
    def update
      @recipe = Recipe.find(params[:id])
      @recipe.update(recipe_params)
      redirect_to new_ingredient_path
    end
#UNSURE OF ABOVE


    def add_ingredients
      @recipe = Recipe.find(params[:id])
    end

    def create_ingredients
      @recipe = Recipe.find(params[:id])

      ingredients = params[:ingredients]

      ingredients.each do |ingredient_id|
        i = Ingredient.find(ingredient_id)

        @recipe.ingredients << i
      end

      redirect_to recipe_path(@recipe)
    end
  end

  # def update_ingredients
  #   # @recipe = Recipe.find(params[:id])
  #   # @recipe.update(recipe_params)
  #   Ingredient.new
  # end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :calories, :people_fed, :cook_time, :course, ingredients: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/ingredients/index.html.erb
<% @ingredients.each do |ingredient| %>
  <%= ingredient.name %>
  <br />
<% end %>
<%= link_to 'Back to recipe list', root_path %>

app/views/ingredients/new.html.erb
<h1>Enter your new Ingredient</h1>
<%= simple_form_for @ingredient do |f| %>
<%= f.input :name %>
<%= f.submit 'Create' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cookbook</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <ul class="nav nav-tabs">
      </ul>
    <%= yield %>
  </div>
  </body>
</html>

app/views/recipes/add_ingredients.html.erb
<!-- <h1>Add Ingredients to <%= @recipe.name %></h1>
<div id="ingredients_table">
<%= simple_form_for @recipe do |f| %>
<%= f.association :ingredients, as: :select, allow_blank: true %>
</div>
<%= submit_tag 'Select this Ingredient'%>
<%= submit_tag 'Add Ingredients Not Listed' %>
<% end %> -->

<h1>Add Ingredients to <%= @recipe.name %></h1>
<%= simple_form_for (@recipe) do |f| %>
<%= f.association :ingredients, as: :select, allow_blank: true, :class=>"x" %>
  <%= submit_tag 'Select this Ingredient', name: 'select'%>
  <%= submit_tag 'Add Ingredients Not Listed', name: 'add' %>
  <% end %>

app/views/recipes/index.html.erb
<h1> List of Current Recipes:</h1>
<br>
<% @recipes.each do |recipe| %>
  <%= recipe.name %>,
  <%= recipe.calories %> calories,
  Feeds <%= recipe.people_fed %>,
  <%= recipe.cook_time %> minutes to cook,
  <%= recipe.course %>
  <br />
<% end %>

<%= link_to 'Ingredients', ingredients_path %> |
<%= link_to 'New Ingredient', new_ingredient_path %> |
<%= link_to 'New Recipe', new_recipe_path %>

app/views/recipes/new.html.erb
<h1>Enter your new Recipe</h1>
<%= simple_form_for @recipe do |f| %>
<%= f.input :name %>
<%= f.input :calories, input_html: {min:'1'} %>
<%= f.input :people_fed, input_html: {min:'1'}, label: 'How many people will this feed?' %>
<%= f.input :cook_time, input_html: {min:'1'}, label: 'Time to Cook(in minutes)' %>
<%= f.input :course, collection: ['Breakfast', 'Lunch', 'Dinner', 'Dessert'] %>
<%= f.submit 'Select Ingredients Required' %>
<% end %>

app/views/recipes/show.html.erb
<h1><%= @recipe.name %></h1>

<h2>Ingredients</h1>

  <table class='table'>
    Number of Ingredients: <%= @recipe.ingredients.count %>
    <% @recipe.ingredients.each do |i| %>
    <tr>
      <td><%= i.quantity(@recipe) %></td> <%# just unsure why this wont show %>
      <td><%= link_to i.name, ingredient_path(i.id) %></td>
    </tr>
    <% end %>
  </table>